import { PROJECT_NAME } from 'containers/App/constants';
const CONTAINER_NAME = 'Photo';

export const FETCH_PHOTOS_REQUEST = `${PROJECT_NAME}/${CONTAINER_NAME}/FETCH_PHOTOS_REQUEST`;
export const FETCH_PHOTOS_SUCCESS = `${PROJECT_NAME}/${CONTAINER_NAME}/FETCH_PHOTOS_SUCCESS`;
export const FETCH_PHOTOS_FAIL = `${PROJECT_NAME}/${CONTAINER_NAME}/FETCH_PHOTOS_FAIL`;

export const SEARCH_PHOTOS_REQUEST = `${PROJECT_NAME}/${CONTAINER_NAME}/SEARCH_PHOTOS_REQUEST`;
export const SEARCH_PHOTOS_SUCCESS = `${PROJECT_NAME}/${CONTAINER_NAME}/SEARCH_PHOTOS_SUCCESS`;
export const SEARCH_PHOTOS_FAIL = `${PROJECT_NAME}/${CONTAINER_NAME}/SEARCH_PHOTOS_FAIL`;

export const GET_PHOTO_REQUEST = `${PROJECT_NAME}/${CONTAINER_NAME}/GET_PHOTO_REQUEST`;
export const GET_PHOTO_SUCCESS = `${PROJECT_NAME}/${CONTAINER_NAME}/GET_PHOTO_SUCCESS`;
export const GET_PHOTO_FAIL = `${PROJECT_NAME}/${CONTAINER_NAME}/GET_PHOTO_FAIL`;

export const SUPPORTED_FONTS = [ 'Roboto', 'Myanmar3', 'Zawgyi', 'Padauk', 'Pyidaungsu', 'Noto Sans Myanmar' ]
